### ISSUE TITLE
HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by z0ranzhang** [dream80/roop_colab#10]
cmd:/content/roop/run.py --execution-provider cuda -s /content/roop_colab/1.jpg -t /content/roop_colab/2.mp4 -o /content/roop_colab/out.mp4 --frame-processor face_swapper face_enhancer --output-video-encoder libx264 --output-video-quality 35 --keep-fps    --temp-frame-format jpg --temp-frame-quality 0
Traceback (most recent call last):
  File "/content/roop/run.py", line 6, in <module>
    core.run()
  File "/content/roop/roop/core.py", line 213, in run
    if not frame_processor.pre_check():
  File "/content/roop/roop/processors/frame/face_swapper.py", line 37, in pre_check
    conditional_download(download_directory_path, ['https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx'])
  File "/content/roop/roop/utilities.py", line 142, in conditional_download
    request = urllib.request.urlopen(url)  # type: ignore[attr-defined]
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by fuyang0811** [comment]
Update the download link. The roop author has ceased his updates and removed certain model files.

**Comment by dream80** [comment]
fixed
