### ISSUE TITLE
运行报错urllib.error.HTTPError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by DreamCloudWalker** [dream80/roop_colab#12]
<img width="1321" alt="image" src="https://github.com/dream80/roop_colab/assets/4676223/350eee50-076b-400f-a79a-d05a75e11262">
cmd:run.py --execution-provider cuda -s /content/roop_colab/1.jpg -t /content/roop_colab/2.mp4 -o /content/roop_colab/out.mp4 --frame-processor face_swapper --output-video-encoder libx264 --output-video-quality 35 --keep-fps    --temp-frame-format jpg --temp-frame-quality 0
Traceback (most recent call last):
  File "/content/roop/run.py", line 6, in <module>
    core.run()
  File "/content/roop/roop/core.py", line 213, in run
    if not frame_processor.pre_check():
  File "/content/roop/roop/processors/frame/face_swapper.py", line 37, in pre_check
    conditional_download(download_directory_path, ['https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx'])
  File "/content/roop/roop/utilities.py", line 142, in conditional_download
    request = urllib.request.urlopen(url)  # type: ignore[attr-defined]
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

**Comment by dream80** [comment]
请确认是否使用了最新版本！

**Comment by DreamCloudWalker** [comment]
直接跑你的roop_v1.3.ipynb的，用的默认选择的Version = "v1.3.2"版本

**Comment by doyoudo** [comment]
一样的问题，用的也是最新版

**Comment by 449684471** [comment]
一样的问题。请楼主修复
<img width="668" alt="image" src="https://github.com/dream80/roop_colab/assets/8488892/4efc0fe5-3ce3-4d61-a8db-a9fba9aedc5a">

**Comment by ZiziBobo** [comment]
礼貌请问各位大佬解决了么😣
