### ISSUE TITLE
报错了！

### ISSUE THREAD

**Issue by hotalex** [dream80/roop_colab#19]
运行到第三项
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/content/tonyff/run.py", line 3, in <module>
    from facefusion import core
  File "/content/tonyff/facefusion/core.py", line 10, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/content/tonyff/run.py", line 3, in <module>
    from facefusion import core
  File "/content/tonyff/facefusion/core.py", line 10, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/__init__.py", line 57, in <module>
    raise import_capi_exception
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError

兄弟帮忙看看！多谢了！

**Comment by dream80** [comment]
已修复
